---
title: "Abstract"
output:
  pdf_document: default
  html_document: default
  word_document: default
---
\phantomsection
\chapter*{Abstract}

Many levels of biological activity contribute to the encoding of specific perceptual experiences. From the discovery that conspecific song playback induces gene expression in a part of the zebra finch brain now referred to as the auditory forebrain, researchers have found increasingly complex roles for the auditory forebrain in song representation. Here we test the idea that the same exact auditory stimulus, varying only in its previously learned association, can induce differential patterns of gene expression. We identify Go/No-Go operant conditioning as a method for generating different meanings associated with a stimulus and develop a suite of software and hardware to conduct this training. We then analyse both the learning of the Go/No-Go behaviour as well as the behavioural response to acute song playback of the stimuli learned during Go/No-Go conditioning. We also examine the expression of _ZENK_, an immediate early gene, in response to the acute playback of one of the trained stimuli. We find evidence to support the idea that Go/No-Go learning requires two separate psychological processes. We also find that acute playback of a learned song stimulus does not elicit quantifiable discrete behavioural states, or indeed any gross measurable behavioural response at all. Finally, we demonstrate that overall levels of _ZENK_ expression in the auditory forebrain do not vary by condition, but that the auditory forebrain responds in a more coordinated way to Go songs than to No-Go, novel, or habituated songs. We conclude that, when active learning is minimised, _ZENK_ expression in the auditory forebrain subtly reflects the previously learned association of stimuli.