---
title: "Conclusion"
output:
  pdf_document: default
  html_document: default
  word_document: default
---
#Conclusion
Starting with the finding that conspecific song playback induces IEG expression in a part of the zebra finch brain now referred to as the auditory forebrain [@Mello1992], researchers have found increasingly complex roles for the auditory forebrain in song representation [@Avey2005a; @Jarvis1995a; @Kruse2004; @Mello1995]. Multiple studies have tested the IEG response to high quality versus low quality song [@Leitner2005; @Woolley2008]. Still more have tested the IEG response when birds are actively engaged in learning [@Gentner2004]. What remained untested was the idea that the same auditory stimulus, varying only in its previously learned association, can induce differential patterns of IEG expression. 

We therefore identified Go/No-Go operant conditioning as a method for generating different meanings associated with a stimulus, and developed the hardware and software necessary to conduct that conditioning. We then analysed how the birds learned the Go versus No-Go discrimination and, using behavioural data, assessed the idea that this operant conditioning leads to two different representations. Next, we characterised the behavioural response to passive acute song playback after discrimination learning in order to understand whether birds' behavioural responses are shaped by this form of playback. Finally, we exposed birds to passive acute song playback and analysed the resulting patterns of neural _ZENK_ expression in order to test our theory that gene expression reflects the neural response to previously learned songs.

##Summary of findings
In Chapter 2, I described Operanter, which is open source hardware and software for avian operant conditioning. In order to conduct the training necessary for the eventual _ZENK_ expression analyses, I developed a suite of Java-based software and non-proprietary hardware. I showed that Operanter can be used to successfully train zebra finches to discriminate between two conspecific songs. The software and hardware is versatile, easily extendable, and inexpensive, and I argue that will allow researchers with small budgets or specific requirements to build operant conditioning setups.

For Chapter 3, I trained birds using Operanter, and characterised their learning of the Go/No-Go discrimination. Most fundamentally, I confirmed that Go/No-Go training leads to discrimination learning for female zebra finches. I also found evidence from both learning and maintenance trials that the Go and No-Go stimuli require different psychological processes. I highlighted large individual differences in when birds prefer to be active, and showed that those preferences correlate with learning rate. I concluded that researchers using Go/No-Go operant conditioning for zebra finches should be conservative when setting learning criteria, and should alter the maximum response latency in light of my findings.

For Chapter 4, I trained a separate group of birds, and recorded their responses to acute passive song playback after learning the Go/No-Go discrimination. I found no evidence that the birds respond differentially to Go and No-Go song playback in this context. I also found no evidence for a behavioural response to the song playback at all, as overall activity levels were similar before and during playback. I argued that this suggests that neurogenomic responses to the same type of playback would represent a neural response to the stimuli, and not overall shifts in activity level.

For Chapter 5, I trained birds using the same methodology characterised in the previous two chapters, and analysed the expression of the IEG _ZENK_ after passive acute exposure to a Go song, a No-Go song, a habituated song, or a novel song. I described the individual differences of _ZENK_ response, but showed that these did not relate to the playback condition. I found that the category of playback did not alter the overall levels of _ZENK_ expression in the auditory forebrain, but that the Go song did elicit a more coordinated response in the auditory forebrain than any of the three other conditions. I concluded that in response to previously learned conspecific songs, differential _ZENK_ expression patterns are subtle, but can be found through graph theory approaches.

##Neural _ZENK_ expression likely reflects neural activity
As a whole, development of the Operanter software and hardware provided the opportunity to train multiple female zebra finches in order to conduct behavioural analyses. The findings from Chapter 3, that Go and No-Go stimuli are learned differentially, inform our understanding of _ZENK_ expression after discrimination learning. By showing that the response latencies to Go and No-Go stimuli are different, and that correct responses to Go and No-Go stimuli are learned at different rates, we add increasing evidence to the body of literature [e.g. @Roy2009] that states that not only do subjects learn to associate one stimulus with a reward and the other stimulus with a punishment, but that these are also learned in different ways. Therefore, _ZENK_ expression in response to the playback of a trained stimulus may reflect either the association (i.e. food reward or darkness punishment), or it may reflect the difference between the processes necessary to respond correctly to Go and No-Go stimuli.

Further, the findings from Chapter 4, that the passive acute song playback does not induce a discrete behavioural state and that there is no evidence for an increase in stress-related behaviours, also inform our understanding of _ZENK_ expression in response to the same passive acute playback. We therefore interpret the _ZENK_ expression results as reflecting neural activity and not physical activity for two reasons. First, there could be brain-wide changes due to metabolic demand [@Tong2001], so the findings in Chapter 4 allow us to rule out a shift in _ZENK_ expression in the auditory forebrain due to large-scale changes. Second, neural _ZENK_ expression can be induced by physical activity, but this is limited to motor regions [@Clark2011; @Feenders2008; @Jarvis1997], and the regions assessed here are auditory regions [see @Dong2008 for evidence that _ZENK_ expression in the auditory forebrain is not related to behavioural response]. Additionally, stress levels can alter the basal level of _ZENK_ [@Park2002], which has likely confounded previous studies of associative learning in the auditory forebrain [@Gentner2004; @Jarvis1995a]. Though we did not present novel or habituated songs to the birds in Chapter 4, the lack of evidence for any kind of a behavioural response to the unsolicited passive playback of Go or No-Go songs suggests that the playback of any conspecific song to a bird who has previously been engaged in operant conditioning of conspecific songs is not particularly surprising or alarming. With no behavioural evidence for increases in stress in response to acute playback of the punished song, we can interpret differences between _ZENK_ expression patterns to Go and No-Go stimuli as representing the categorical differences between the stimuli, and not simply varying stress levels. 

Therefore, the _ZENK_ expression results from Chapter 5 can be interpreted with increased confidence to reflect a neural response to the stimulus category. On the basis of this evidence, we believe that the lack of a difference in overall _ZENK_ expression levels in the auditory forebrain is due to similar levels of novelty, and therefore salience, of all of the conditions. That is, the unsolicited and rapid nature of all of the song playbacks may have rendered the novel condition insufficiently different from even the habituated condition [@Kruse2004]. In this context, where female birds have habituated to social isolation over a period of weeks, novel and habituated conspecific songs give rise to the same overall levels of _ZENK_ expression in the auditory forebrain, perhaps reflecting the sparseness of conspecific song exposure over a long period. To our knowledge, this is the first evidence that the novel/familiar difference in _ZENK_ expression across the auditory forebrain is not absolute.

##Limitations and future research
It is, of course, necessary to address the limitations of the current research. Most simply, the birds in all three chapters were from different cohorts, and it is therefore impossible to conclude with certainty that the behaviour of the birds used for _ZENK_ expression analysis was the same as those in the behaviour analyses. Additionally, with only five birds per condition in the analysis of behavioural response to passive song playback, and five or six birds per condition in the analysis of _ZENK_ expression, we did not have the power to detect subtle changes. However, as there were numerous precedents for large effects on _ZENK_ expression [@Mello1992; @Mello1995], and previous similar studies regularly use four to six individuals per condition [@Gentner2004; @Ribeiro1998], we suggest that this was an appropriate decision.

One major concern in the interpretation of the enhanced coordination of _ZENK_ response to the Go stimulus relates to the question of what _ZENK_ expression actually reflects in this context. IEG expression in the zebra finch auditory forebrain has been shown to encode both novel [@Mello1992] and previously learned stimuli [@Gentner2004]. In this context, where the stimulus discrimination has been previously learned but is no longer being actively maintained, the _ZENK_ response could be functioning either as a read-out of the memory [e.g. @Liu2012] or it could be assisting in the formation of a new memory [@Minatohara2016]. Though we specifically chose the number of song repetitions to reduce the likelihood of extinction learning [e.g. @Jarvis1995a], we cannot rule out the possibility that the _ZENK_ expression in response to these passive playbacks reflects that.

Future research would ideally explicitly address this, by testing some individuals with passive exposure and other individuals still engaged with the operant apparatus, although this would raise complications related to motor behaviours and motivation. Additionally, it remains unclear whether the birds learned to prefer the Go song during the operant conditioning, or whether the coordinated _ZENK_ response to Go songs is due to the learning of the Go response. To test this idea, and to therefore be able to interpret the findings in the context of the female song preference literature [@Leitner2005; @Woolley2008], song preference could be tested before and after Go/No-Go training using the same operant setup [@Holveck2007]. 

##Does operant conditioning alter the neurogenomic response to song presentation?
This thesis provides the first evidence that in response to passive playback following the operant conditioning of two conspecific songs, _ZENK_ expression in the auditory forebrain is more coordinated to Go songs than to No-Go songs. Therefore, we have shown that operant conditioning does subtly alter the neurogenomic response to song presentation. We also demonstrated that acute song playback of novel and habituated songs does not necessarily drive differential expression of _ZENK_ in the zebra finch auditory forebrain. We conclude that although there is no evidence that _ZENK_ expression varies across the auditory forebrain in response to our stimuli, differential networks of activity can be induced depending on the valence of the previously learned stimulus’ association.