---
title: "Introduction"
output: html_document
---


#Introduction

Many levels of biological activity of the brain are involved in the encoding of specific perceptual experiences. Though most work to date has focused on the role of synaptic activity [@Dubnau2003], gene expression has been posited as a mechanism through which memories are stored [@Clayton2000]. Acute and salient experiences induce changes in fast-responding genes that have multiple downstream effects (immediate early genes; IEGs) [e.g. @Jarvis1997a; @Wheeler2013] and neurons that express IEGs are involved in memory formation [@Minatohara2016]. Long-term memory formation is impaired for mice that do not have the IEG _Arc_ [@Plath2006a], and juvenile zebra finch males do not learn tutor song accurately when a pathway associated with the IEG _ZENK_ is disrupted [@London2008]. Moreover, IEGs have been shown to be differentially neurally expressed in response to stimuli with varying levels of salience and novelty [@Mello1992; @Terpstra2006]. What remains unclear is whether the presentation of an identical stimulus, which through experience has acquired a meaning, elicits differing neuroanatomical distributions of an IEG. If so, the neuroanatomical distribution of that IEG would reflect the meaning of that stimulus, and provide new evidence as to how the brain encodes memories.

For this thesis, I test this idea using a combination of behavioural and molecular techniques, and the auditory discrimination abilities of a songbird, the zebra finch (_Taeniopygia guttata_). In this introduction, I begin by reviewing the evidence for perceptual learning and discrimination of auditory patterns in songbirds. I then describe the use of a particular IEG (_ZENK_) as a tool for studying the anatomical distribution of plasticity-related neural activity. Finally, I explain operant conditioning techniques used to shape the associations an animal has with a stimulus, and how this can be used to investigate the neural encoding of those associations.

##Neural encoding of song stimuli in songbirds

###Songbirds as a model species for auditory memory
Members of the songbird clade, especially the zebra finch, are frequently used as a model species for the investigation of auditory perception and auditory memory. Both male zebra finches and humans have a sensitive period for vocal learning as well as similar learning phases (i.e. a social phase followed by/overlapping with a sensorimotor phase that begins with babbling) [@Doupe1999]. Although female zebra finches do not learn to produce song, they do learn to recognise individuals by their songs, and their preference for song is shaped by early life experiences [@Clayton1988; @Holveck2014; @Lauay2004]. Further, the neuroanatomy of the song system is fairly well understood in the songbird [@Doupe2005; @Mello2004]. 

In the songbird brain, for both males and females, auditory input arrives in the MLd (dorsal lateral nucleus of the mesencephalon) in the brainstem, where there is some preliminary tuning of neural responses (e.g. functional MRI evidence suggests greater activation in response to conspecific song than heterospecific song in the male zebra finch left MLd [@Poirier2009]). The MLd projects to the nucleus ovoidalis, which projects auditory information to be filtered through Field L, a collection of tonotopically organised regions similar to the mammalian auditory cortex [@Gehr1999]. Field L projects to CLM (caudolateral mesopallium) and NCM (caudomedial nidopallium), which in turn project to CMM (caudomedial mesopallium) [@Moorman2011; @Vates1996]. The part of the brain that includes NCM, CMM, and Field L2 has been referred to as the auditory forebrain [@Theunissen2004]. Regions in the auditory forebrain then project to HVC and RA, which are part of the song production system in male songbirds.

Evidence from large-scale gene expression studies indicates that the auditory forebrain is involved in complex auditory processing. Within the auditory forebrain, at least five miNAs vary depending on whether a bird has been exposed to a song or to silence [@Gunaratne2011]. One of these, miR-2954, affects the expression of around 1000 downstream mRNAs, suggesting that this single miRNA might mediate a large network of neurogenomic changes that are involved in song perception [@Lin2014]. Further, many of the genes affected by miR-2954 are downregulated when birds are exposed to song to which they have habituated [@Dong2009a]. Dong et al. (2009) found that detection of this habituation profile does not require presentation of the stimulus immediately before tissue collection; rather, simple exposure to repeated presentation of a single song can induce large-scale changes in gene expression the day before tissue collection. These broad dynamic shifts suggest that patterns of gene expression in the auditory forebrain contribute to, or at least reflect, recent exposure to song stimuli.

Connectivity between regions in the auditory forebrain is rich and complex [@Vates1996]. Field L2 has reciprocal projections to CLM, which has reciprocal projections to CMM, which has reciprocal projections to NCM. Despite the interconnectivity within the auditory forebrain, different regions, and even subregions, display vastly different responses to auditory stimuli. For example, some neurons in Field L and CMM selectively respond to conspecific songs, but other neurons selectively respond to white noise [@Grace2002]. Further, medial parts of Field L and CMM exhibit greater selectivity for conspecific songs than lateral parts [@Grace2002]. In contrast to the similarity of electrophysiological responses in Field L and CMM in that particular study, Mello et al. [-@Mello1992] found that in response to conspecific song playback, an immediate-early gene called _ZENK_ is expressed in NCM and CMM, but not in Field L2. NCM and CMM also show differential responses to song playback; _ZENK_ expression in female zebra finch NCM is higher in response to conspecific song than heterospecific song, but _ZENK_ expression in CMM is similar in response to both conspecific and heterospecific song [@Bailey2002].

For some who study male song production, the auditory forebrain has been characterised as a secondary auditory processing centre that receives auditory input and feeds into the male songbird's song production system, and much work has been done to understand the processing of tutor song and bird's own song in the auditory forebrain [see @Mooney2009; @Theunissen2004]. However, the role of the auditory forebrain is more likely that of a general song processor for both males and females. For example, for female zebra finches, who do not sing, temporary inactivation of NCM leads to females failing to show a preference for males singing natural song [@Tomaszycki2014]. NCM has been further implicated in the processing of sexually relevant stimuli for females; for female starlings, who prefer longer songs, @Gentner2000 found that _ZENK_ expression was higher in ventral NCM for females exposed to longer songs than females exposed to shorter songs, but that expression was uniform in response to both song lengths in CMM. In contrast, for female zebra finches, who prefer directed song to undirected song, _ZENK_ expression in NCM is modulated by familiarity of songs, whereas _ZENK_ expression in CMM is modulated by the directedness of the song as directed songs tend to be preferred over undirected songs [@Woolley2008]. Similarly, ZENK  expression in CMM is higher for female zebra finches who are exposed to their father's song than for birds exposed to novel songs [@Terpstra2006], and _ZENK_ expression in CMM is higher for female canaries who are exposed to sexy syllables compared to nonsexy syllables [@Leitner2005]. In one surprising study of natural and time-distorted songs played to female zebra finches, both NCM and CMM responded with similar increases in _ZENK_ expression in response to the time-distorted songs [@Lampen2014]. Therefore, for female songbirds, the auditory forebrain responds to birdsong in complex ways, with some aspects of preference, salience and familiarity leading to differential expression in NCM, and others leading to differential expression in CMM.

One potential explanation for the range of effects seen in the auditory forebrain is that subregions, which are not clearly visible using common neuroanatomical staining techniques such as hematoxylin and eosin, respond differentially. For example, _ZENK_ expression in response to song playback decreases from medial to lateral sections in NCM, but the same effect of laterality is not found for CMM [@Gentner2000]. Further, responses to auditory stimuli within the NCM vary on the dorsoventral axis; for canaries, dorsal NCM preferentially responds to low frequencies, and ventral NCM responds to high frequencies [@Ribeiro1998]. For the mesopallium, despite discrete nomenclature for CMM and CLM, these two regions are generally separated by their distance from the midline, and they do not respond similarly to all stimuli [@Jeanne2011]. Some reports collected data from CMM between 320-700 $\mu$m from the midline [@Woolley2008], and a frequently used zebra finch atlas shows CMM from 200-1700um from the midline [@zebraOnline]. Multiple studies provide no clear indication of laterality [e.g. @Jarvis1995a; @Lampen2014]. Given the complex multi-dimensional nature of responses to auditory stimuli in the auditory forebrain, there is a clear need for high spatial resolution, which modern methods, such as RNASeq and fMRI of the entire auditory forebrain, cannot provide.

###Probing the neurobiology of song recognition using the _ZENK_ gene
_In situ_ hybridisation is one method that provides extremely fine spatial resolution. In contrast to electrophysiology, which also provides high spatial resolution, _in situ_ hybridisation supports the imaging of large areas of tissue. _In situ_ hybridisation suffers from low temporal resolution, and when studying neural tissue, only one time-point per animal can be assessed. Despite this, IEGs, which are genes that respond rapidly to stimuli and have a broad range of downstream effects, have been widely used in neuroscience to measure activity and learning in the brain [@Clayton2000; @Minatohara2016]. Within the avian neuroscience literature, the IEGs _ZENK_ (and its protein product ZENK) [@Mello1992; @Lampen2014], _c-fos_ [@Hall2014; @Kimpo1997], and _BDNF_ [@Li2000] have all been used. Of these, the most frequently measured is _ZENK_. _ZENK_ is the avian homologue of and an acronym for _zif268_, _egr-1_, _NGFI-A_, and _Krox24_ [@Mello1992], and though NCBI has standardised the use of _egr-1_, I will refer to the gene here as _ZENK_ due to its longstanding use in the avian literature. Within the auditory forebrain, expression of _ZENK_ correlates strongly with electrophysiologically measured activity in response to songs [@Chew1995a; @Chew1996; @Stripling1997]. 

The last twenty-six years have been fruitful in characterising the _ZENK_ gene response in the auditory forebrain; conspecific songs elicit strong _ZENK_ expression in NCM and CMM and this peaks 30 minutes after acute playback of the song [@Mello1992; @Mello1994]. _ZENK_ expression in NCM and CMM varies depending on the salience of features. For instance, _ZENK_ expression is, on the whole, greater in response to conspecific songs than heterospecific songs, and greater in response to heterospecific songs than tones or silence [@Mello1992]. The _ZENK_ response is also likely to occur in natural settings: only 10 repetitions of a conspecific song are necessary to induce the full _ZENK_ response [@Kruse2000], it can be induced in wild birds listening to acute playbacks [@Jarvis1997a], and _ZENK_ expression is higher across the auditory forebrain for birds in an aviary compared to birds isolated in a sound attenuation chamber [@George2016]. Further, the _ZENK_ response in NCM and CMM habituates to repeated song playback [@Mello1995]. This effect is song-specific; if played a novel song, the _ZENK_ response in the auditory forebrain recovers [@Mello1995]. Further, this recovery from habituation can occur with the same song played in a new context, such as from a different perceived spatial location [@Kruse2004]. Whether the stimulus is conspecific or heterospecific, novelty, and spatial location are all examples of varying levels of inherent salience, and there is ample evidence that the _ZENK_ response in the auditory forebrain encodes this. 

###Associative learning in the auditory forebrain
Evidence also demonstrates that the _ZENK_ response reflects learned salience. Stimuli with no differences in inherent salience, but that have been associated with a stimulus with inherent salience, vary in the levels of _ZENK_ they induce. Jarvis et al. [-@Jarvis1995a] found that, using a classical conditioning methodology, _ZENK_ expression in NCM and CMM is greater when a song is paired with a shock than when songs and shocks are played/given at the same rate but unpaired. For starlings, Gentner et al. [-@Gentner2004] argue that novel songs elicit high levels of ZENK protein induction in NCM, whereas songs that birds have been trained to associate with a food reward or lights-out punishment elicit similarly low levels of ZENK in NCM. In contrast, in CMM, they found that the novel condition elicited the highest density of ZENK, followed by the trained songs, with silence significantly lower than novel and trained songs [@Gentner2004]. This study confounded stress and associative learning, and as the _ZENK_ response can be altered by placing a bird under stress [@Park2002], the findings are difficult to interpret. However, it is clear that subregions of the auditory forebrain respond in complex ways to auditory stimuli with learned associations.

Electrophysiological studies have also aided our understanding of the role of the auditory forebrain in associative auditory learning. In Gentner & Margoliash [-@Gentner2003], electrophysiological recordings of anaesthetised starlings' CMM demonstrated that CMM neurons respond more to songs that have been associated with reward than to songs that have been associated with punishment. They also found a greater neural response to songs associated with punishment than to novel songs [NB: in direct contrast to @Gentner2004]. A more recent study has shown that after learning to associate one song with a reward and another song with a punishment, neurons in awake birds' NCM responded more to rewarded songs than punished songs, with novel songs eliciting middling responses [@Bell2015]. In CMM, neurons were most responsive to rewarded songs, less responsive to punished songs, with novel songs eliciting a very low level of responding [@Bell2015]. Bell et al. (2015) therefore replicated Gentner & Margoliash's (2004) finding that CMM preferentially responds to stimuli that have been intensely trained to be associated with a reward or punishment.

Despite this wealth of both gene expression and electrophysiological investigations into associative learning in the auditory forebrain, no studies have yet controlled the song stimulus experience tightly enough to determine if gene expression is related to the stimulus’ association. To do so, birds must be trained to associate two song stimuli with two different conditioned stimuli, and the presentation of the song stimulus, to which the _ZENK_ response is measured, must come after confirmation that the birds have learned the associations. One simple way to achieve this is using Go/No-Go learning, an operant conditioning paradigm.

##Use of operant conditioning to shape stimulus association

Operant conditioning is a form of learning whereby behaviour is altered by experience; effectively, it is the form of learning that leads to habit formation [@Staddon2003]. In contrast to classical conditioning, where a stimulus is associated with an outcome, operant conditioning creates an association between a behaviour and an outcome [@Kirsch2004]. Early studies demonstrated that random behaviours can be shaped by the regular presentation of rewarding feedback and highlighted that pattern-seeking is fundamental to learning processes [@Skinner1948]. The earliest work into operant conditioning focused on fundamental variables such as trial timing [@Skinner1938] and the relationship between reward frequency and the conditioned behaviour [@Herrnstein1961]. However, more recently, the role of cognition, such as perceived choice [@Washburn1991] and motivation [@Lawrence1989], in operant responding has also been investigated. Fortunately for avian researchers, much of the early work into operant conditioning was conducted on pigeons [@Brown1968], and a wide array of operant conditioning paradigms, such as the 2-alternative forced choice task and Go/No-Go, have been developed and extended for use in understanding bird behaviour [@Hulse1995].

Go/No-Go training is a form of conditioning whereby an animal learns to associate one stimulus with a positive reinforcement and a second stimulus with a positive punishment. It does this by way of operant conditioning; i.e. it learns to associate a behaviour with a stimulus, which is associated with a reinforcement or punishment. More simply, the animal is presented with two stimuli (the Go stimulus and No-Go stimulus) and must learn that when it encounters the Go stimulus it must make the Go behaviour (e.g. pecking at a sensor). If it does so, the Go behaviour is reinforced (with, for example, a food reward). If it does not do so, the animal does not receive any reinforcement. However, when the animal encounters the No-Go stimulus it must make the No-Go behaviour (i.e. withholding the Go response, or simply not responding). If the animal makes the Go behaviour in response to the No-Go stimulus, the behaviour is punished (with, for example, the lights going out). If the animal makes the No-Go behaviour in response to the No-Go stimulus, the response is neither reinforced nor punished. In this way, the bird learns to associate the Go stimulus with a Go behaviour and a reinforcement, and also learns to associate the No-Go stimulus with a No-Go behaviour and a punishment. This learning of differential associations is often characterised as discrimination learning.

###Operant conditioning in songbird research
Operant conditioning has been used as a tool in many bird studies to assess perceptual abilities. For example, just-noticeable differences in harmonics and the effect of duration on similarity comparisons can be derived simply from patterns of responses [@Beckers2003; @Lohr1998]. One common assay is to test how birds generalise to novel stimuli once learning the discrimination of the initial training stimuli. For example, recent investigations have highlighted that starlings do not generalise tonal sequences when the pitch and timbre are altered [@Bregman2016] and that individual zebra finches use different tactics to learn artificial grammar rules [@VanHeijningen2013]. Though these reports use different forms of operant conditioning (e.g. 2-AFC, Go/No-Go), what they have in common is the quantification of responses to novel/unconditioned stimuli, and an assumption that those responses reflect whether the subjects perceive the unconditioned stimuli as more like one or the other of the conditioned stimuli. These studies often fail to recognise that an inherent bias in responding (such as an overall likelihood to make the Go behaviour in response to all stimuli) can affect the statistical outcomes, especially when reporting response probabilities. Evidence that Bengalese finches employ multiple cognitive tactics to learn the Go/No-Go discrimination further complicates these analyses [@Morisaka2009]

In contrast, we will use Go/No-Go operant conditioning solely as a tool to train the birds to associate one song with reward and a pecking behaviour and the other with punishment and no behavioural response. Although evidence suggests that some songbirds may preferentially learn to recognise the No-Go stimulus [@Morisaka2009], and a range of human-based studies suggest that the Go and the No-Go responses are inherently unbalanced and require different cognitive processes [@Roy2009; but see @Criaud2013], we suggest that the clear differential responses to Go and No-Go stimuli (i.e. the Go and No-Go behaviour) indicate that some form of associative learning has occurred. For the purposes of understanding whether gene expression varies in response to stimuli learned through operant conditioning, we therefore need not be concerned with issues of learning strategies and motivation, though we recognise that the specific patterns of gene expression may rely on these variables.

##Aims and objectives
We will combine molecular neurobiology with behavioural psychology to determine if differential IEG expression reflects memories of perceptual experiences. Go/No-Go operant conditioning provides us with a powerful method for forming associative memories. _In situ_ hybridisation of the IEG _ZENK_ allows us to assess neural gene expression with high spatial resolution. We will first train a bird to discriminate between one song (Go stimulus) and a second song (No-Go stimulus). Then we will play one of those two songs immediately before collecting tissue for _ZENK_ _in situ_ hybridisation. Finally, we will use the pattern of _ZENK_ induction to assess which brain regions are involved in the perception of previously learned stimuli. 

First, I present Operanter, a new suite of hardware and software that allows us to inexpensively conduct avian auditory operant conditioning. We successfully developed, from the ground up, Java-based software and non-proprietary hardware that has enabled us to train around 40 female zebra finches thus far.

Second, I use a fine-grained analysis of operant conditioning learning and maintenance to characterise individual differences in Go/No-Go learning, and to better understand the processes underlying the Go and No-Go responses. We find that birds' responses to two conspecific songs initially have a Go bias, and that birds are slower to learn the correct response to No-Go stimuli. We also argue that response latencies to Go and No-Go stimuli suggest separate cognitive processes for these responses. Finally, we show that the time of day a bird is preferentially active relates to the bird's learning rate.

Third, I demonstrate that despite the profound differences in response to Go and No-Go stimuli during operant conditioning, avian responses to acute playbacks of the trained stimuli do not differ. Using an array of analytical techniques, we find that patterns of behaviour do not vary during playback of the trained stimuli, and we argue that this means that differences in neural gene expression cannot be caused simply by differences in physical activity levels.

Fourth, I show that overall levels of _ZENK_ gene expression do not vary across the auditory forebrain in response to Go, No-Go, novel and habituated songs. Responses to novel and habituated songs do not elicit the same strikingly differential patterns of expression as found in previous experiments. However, using graph theory approaches, I demonstrate that the auditory forebrain responds in a more coordinated way in response to Go songs than in response to No-Go, novel, or habituated songs.

Finally, I summarise my findings and conclude that operant conditioning experiments, in conjunction with _in situ_ hybridisation, provide rich anatomical detail that allows us to investigate the neurogenetic basis for encoding associative memories.
